#!/bin/bash
firefox  \
-new-tab questionablecontent.net \
-new-tab girlswithslingshots.com \
-new-tab somethingpositive.net \
-new-tab darthsanddroids.net \
-new-tab xkcd.com \
-new-tab gunnerkrigg.com \
-new-tab drmcninja.com \
-new-tab giantitp.com \
-new-tab goblinscomic.com \
-new-tab dresdencodak.com

